export const petTips = [
  "Ensure your pet has fresh water daily to stay hydrated.",
  "Brush your pet's fur regularly to prevent matting and reduce shedding.",
  "Schedule annual vet check-ups to catch health issues early.",
  "Provide your pet with a balanced diet suited to their breed and age.",
  "Clean your pet’s bedding and toys to prevent bacteria buildup.",
  "Train your pet consistently to establish good behavior and habits.",
  "Socialize your pet early to help them feel comfortable around others.",
  "Exercise your pet daily to keep them healthy and prevent obesity.",
  "Brush your pet’s teeth regularly to avoid dental issues.",
  "Create a safe, cozy spot for your pet to relax and feel secure.",
  "Keep your pet's vaccinations up-to-date to prevent diseases.",
  "Use a pet-safe flea and tick treatment to protect your pet.",
  "Trim your pet’s nails regularly to prevent painful overgrowth.",
  "Teach your pet basic commands like 'sit,' 'stay,' and 'come.'",
  "Provide toys and puzzles to keep your pet mentally stimulated.",
  "Introduce new pets slowly to avoid stress and conflict.",
  "Use positive reinforcement when training your pet.",
  "Never leave your pet in a hot car, as it can lead to heatstroke.",
  "Ensure your pet has a comfortable place to sleep.",
  "Give your pet regular baths with pet-friendly shampoo.",
  "Keep a first-aid kit handy for pet emergencies.",
  "Microchip your pet so they can be identified if lost.",
  "Play with your pet daily to strengthen your bond.",
  "Regularly check your pet for signs of illness or discomfort.",
  "Make sure your pet has identification tags on their collar.",
  "Rotate toys to keep your pet interested in playtime.",
  "Avoid giving your pet food that can be toxic, like chocolate.",
  "Spend quality time with your pet each day to keep them happy.",
  "Provide a scratching post for cats to maintain their claws.",
  "Protect your pet’s paws from hot or cold pavement.",
  "Train your pet to be comfortable in a crate or carrier.",
  "Keep household cleaners out of reach, as many are toxic to pets.",
  "Create a pet-friendly space in your home that’s safe and fun.",
  "Always supervise pets around young children.",
  "Establish a routine for feeding, play, and bathroom breaks.",
  "Keep poisonous plants out of your pet's reach.",
  "Make regular grooming appointments for pets with thick coats.",
  "Avoid feeding your pet table scraps to prevent obesity.",
  "Consider pet insurance for unexpected medical costs.",
  "Use pet-safe products to clean your home.",
  "Monitor your pet’s weight and adjust food as needed.",
  "Train your dog to walk on a leash without pulling.",
  "Allow your pet to have quiet time when they need it.",
  "Know the signs of pet stress, such as pacing or excessive licking.",
  "Provide outdoor access or stimulation for pets who enjoy it.",
  "Keep electrical cords out of reach from chewing pets.",
  "Use a harness instead of a collar for small dog breeds.",
  "Rotate food flavors for variety, but stick to pet-safe choices.",
  "Prepare for fireworks or loud noises by creating a calm space.",
  "Use a pet-friendly shampoo and avoid over-bathing.",
  "Monitor your pet’s interaction with other animals to prevent fights.",
  "Keep your pet’s environment clean and free from hazards.",
  "Offer healthy treats during training to reinforce good behavior.",
  "Take your dog for regular walks to explore and exercise.",
  "Use baby gates to limit access to unsafe areas in the home.",
  "Adjust your pet’s diet based on age, activity, and health needs.",
  "Reward your pet with treats or praise to reinforce learning.",
  "Provide enrichment activities like fetch or puzzle toys.",
  "Watch for changes in your pet’s behavior as it can signal health issues.",
  "Secure trash cans to prevent pets from getting into harmful items.",
  "Groom your pet regularly to check for lumps, fleas, or skin issues.",
  "Keep a regular feeding schedule to avoid digestive issues.",
  "Be patient with training and use positive methods.",
  "Consider crate training for easier travel with pets.",
  "Use a pet-safe paw balm for pets who walk on rough surfaces.",
  "Allow your pet time to adjust to new environments gradually.",
  "Provide a cozy blanket or bed for your pet’s comfort.",
  "Make time for daily play to keep your pet happy and fit.",
  "Ensure your pet’s collar fits properly and is not too tight.",
  "Introduce grooming tools like brushes and clippers slowly.",
  "Check your pet’s ears regularly for signs of infection.",
  "Monitor older pets closely for signs of arthritis or discomfort.",
  "Always supervise your pet around bodies of water.",
  "Provide plenty of fresh air and sunlight for your pet.",
  "Use pet-friendly sunscreen on pets with thin or light-colored fur.",
  "Set up a quiet space for your pet to retreat to during stressful events.",
  "Check the temperature of outdoor areas before letting your pet out.",
  "Use pet-safe cleaning products on floors and furniture.",
  "Encourage positive interactions with people and other pets.",
  "Be mindful of your pet’s energy level and provide rest if needed.",
  "Give older pets extra support, like ramps or joint supplements.",
  "Train your pet to tolerate car rides for smoother travel experiences.",
  "Regularly inspect your pet’s food for any spoilage or contamination."
];
